#!/bin/bash

function compile() {
    local ename=""
    local flags=""
    local use_hit=0
    local use_atm=0
    local use_turbines=0
    local use_ls=0
    local use_mpi=0
    local use_cps=0
    for arg in "$@"
    do
        if [ $arg == "-" ]; then
            ename="${ename}"
        elif [ $arg == "mpi" ]; then
            ename="${ename}-mpi"
            flags="${flags} -DUSE_MPI=ON"
            use_mpi=1
        elif [ $arg == "cps" ]; then
            ename="${ename}-cps"
            flags="${flags} -DUSE_CPS=ON"
            use_cps=1
        elif [ $arg == "HIT" ]; then
            ename="${ename}-HIT"
            flags="${flags} -DUSE_HIT=ON"
            use_hit=1
        elif [ $arg == "streaks" ]; then
            ename="${ename}-streaks"
            flags="${flags} -DUSE_STREAKS=ON"
        elif [ $arg == "ls" ]; then
            ename="${ename}-ls"
            flags="${flags} -DUSE_LVLSET=ON"
            use_ls=1
        elif [ $arg == "turbines" ]; then
            ename="${ename}-turbines"
            flags="${flags} -DUSE_TURBINES=ON"
            use_turbines=1
        elif [ $arg == "ATM" ]; then
            ename="${ename}-ATM"
            flags="${flags} -DUSE_ATM=ON"
            use_atm=1
        elif [ $arg == "exout" ]; then
            ename="${ename}-exout"
            flags="${flags} -DOUTPUT_EXTRA=ON"
        elif [ $arg == "dyntn" ]; then
            ename="${ename}-dyntn"
            flags="${flags} -DUSE_DYN_TN=ON"
        elif [ $arg == "safety_off" ]; then
            ename="${ename}-safety_off"
            flags="${flags} -DUSE_SAFETYMODE=OFF"
        elif [ $arg == "cgns" ]; then
            ename="${ename}-cgns"
            flags="${flags} -DUSE_CGNS=ON"
        else
            echo "Invalid compile option $arg...."
            exit 1
        fi
    done

    # Run compilation test
    echo "Compiling lesgo${ename}..."
    rm -r bld${ename} &> temp.out
    cmake $flags . -Bbld${ename} &> temp.out
    cmake --build bld${ename} &> bld${ename}/cmake.out
    local warns=$(grep -c "Warning:" "bld${ename}/cmake.out")
    local errs=$(grep -c "Error:" "bld${ename}/cmake.out")
    echo "Finished compiling lesgo${ename} with $warns warning(s) and $errs error(s)."

    # Pre-runtime copying of data and editing for lesgo.conf
    cp lesgo.conf bld${ename}
    if [ $use_ls == 1 ]; then
        cp trees.conf bld${ename}
    fi
    if [ $use_turbines == 1 ]; then
        cp -r input_turbines bld${ename}
    fi
    if [ $use_atm == 1 ]; then
        cp -r inputATM bld${ename}
    fi
    if [ $use_hit == 1 ]; then
        cp -r HITData bld${ename}
    fi
    cd bld${ename}
    if [ $use_ls == 1 ]; then
        sed -ib -e "s/Lx.*=.*/Lx = 1.0/" lesgo.conf
        sed -ib -e "s/Ly.*=.*/Ly = 1.0/" lesgo.conf
        sed -ib -e "s/Lz.*=.*/Lz = 1.0/" lesgo.conf
    fi

    # Run with proper setup and number of processors
    if [ $use_cps == 1 ]; then
        mkdir red
        mkdir blue
        cp -r lesgo${ename} lesgo.conf trees.conf input_turbine inputATM HITDATA red &> temp.out
        cp -r lesgo${ename} lesgo.conf trees.conf input_turbine inputATM HITDATA blue &> temp.out
        sed -ib -e "s/nproc.*=.*/nproc = 1/" red/lesgo.conf
        sed -ib -e "s/nproc.*=.*/nproc = 1/" blue/lesgo.conf
        sed -ib -e "s/inflow.*=.*.false./inflow = .true./" blue/lesgo.conf
        mpirun -wdir red -np 1 ./lesgo${ename} : -wdir blue -np 1 ./lesgo${ename} > lesgo.out && echo "Finished running lesgo${ename} successfully." || echo "lesgo${ename} failed at run time with error code $?."
    else
        if [ $use_mpi == 1 ]; then
            sed -ib -e "s/nproc.*=.*/nproc = 2/" lesgo.conf
            mpirun -np 2 ./lesgo${ename} &> lesgo.out && echo "Finished running lesgo${ename} successfully." || echo "lesgo${ename} failed at run time with error code $?."
        else
            ./lesgo${ename} &> lesgo.out && echo "Finished running lesgo${ename} successfully." || echo "lesgo${ename} failed at run time with error code $?."
        fi
        cd ..
    fi
}
export -f compile

# compile ls
list=( '-' HIT streaks ls turbines ATM exout dyntn safety_off)
echo "will cite" | parallel --citation &> temp.out
parallel compile ::: "${list[@]}"
parallel compile ::: "mpi" ::: "${list[@]}"
# compile mpi exout
# compile mpi cps
rm temp.out

echo
echo "lesgo testing complete."